name: Create Pull Request with cherry-pick
on:
  push:
    branches:
      - dev
jobs:
  create_cherry_pick_and_pull_request:
    runs-on: ubuntu-latest
    name: create_cherry_pick_and_pull_request:
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: GHA cherry-pick and PR
      uses: albertoff7/gha-cherry-pick@master
      with:
        # This is the branch you want to merge your last cherry-picked commit into.
        pr_branch: 'release'
        # This is the "parent" depth at which cherry-picking do.
        pr_cherry_parent: '1'
      env:
        # Enviroments variables that we need
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: me@me.me
        DRY_RUN: false
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
